// <auto-generated />
namespace FancyImageUploader.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class test_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201406121436315_test_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
