// <auto-generated />
namespace FancyImageUploader.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class file_model_added_sizeChar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(file_model_added_sizeChar));
        
        string IMigrationMetadata.Id
        {
            get { return "201406141337235_file_model_added_sizeChar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
